DROP TABLE PESSOA               CASCADE CONSTRAINTS;
DROP TABLE FUNCIONARIO          CASCADE CONSTRAINTS;
DROP SEQUENCE TRG_PESSOA_ID;
DROP SEQUENCE TRG_FUNCIONARIO_ID;


CREATE TABLE PESSOA (
    ID_PESSOA       NUMBER PRIMARY KEY,
    NOME            VARCHAR2 (100) NOT NULL,
    TELEFONE        VARCHAR2(20) NOT NULL,
    EMAIL           VARCHAR2(100) NOT NULL,
    CPF             VARCHAR2(14) NOT NULL
);

CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO  NUMBER PRIMARY KEY,
    ID_PESSOA       NUMBER,
    CARGO           VARCHAR2(50),
    SALARIO         NUMBER NOT NULL,
    COMISSAO        NUMBER,
    TURNO           VARCHAR2(20) NOT NULL,
    DATA_ADMISSAO   DATE NOT NULL,
    CONSTRAINT FK_FUNCIONARIO_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA)
);

CREATE SEQUENCE SEQ_PESSOA_ID START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_PESSOA_ID
BEFORE INSERT ON PESSOA
FOR EACH ROW
BEGIN
  :new.ID_PESSOA := SEQ_PESSOA_ID.NEXTVAL;
END;


CREATE SEQUENCE SEQ_ID_FUNCIONARIO START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_FUNCIONARIO_ID
BEFORE INSERT ON FUNCIONARIO
FOR EACH ROW
BEGIN
  :new.ID_FUNCIONARIO := SEQ_ID_FUNCIONARIO.NEXTVAL;
END;




